###
#checking api with hello world
GET http://localhost:8080/hello

###
#create user api with post method 
POST http://localhost:8080/create-user

{
    "username":"bishan890",
    "password":"bishan123"
}

###
# login user
POST http://localhost:8080/login

{
    "username":"bishan890",
    "password":"bishan123"
}

###
#create scrapping
POST http://localhost:8080/scrape
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjRiOGMzZWUwLTYyOWYtNGQwMy04ODI1LTdjNzRhM2EwNWFmZiIsInVzZXJJZCI6MSwidXNlcm5hbWUiOiJiaXNoYW4iLCJpc3N1ZWRfYXQiOiIyMDIyLTAzLTI4VDA3OjI0OjQxLjAxOTk0MDQ2OFoiLCJleHBpcmVkX2F0IjoiMjAyMi0wMy0yOFQxMTozNDo0MS4wMTk5NDA2NDhaIn0.eG8aAoje7s_bENwb06kM1cSgo8y7eJgfOUs-p8KRAaM

{
    "scrape_url":["https://gin-gonic.com/","https://go.dev/"]
}
###
#Get scrapping data
GET http://localhost:8080/scrape
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjRiOGMzZWUwLTYyOWYtNGQwMy04ODI1LTdjNzRhM2EwNWFmZiIsInVzZXJJZCI6MSwidXNlcm5hbWUiOiJiaXNoYW4iLCJpc3N1ZWRfYXQiOiIyMDIyLTAzLTI4VDA3OjI0OjQxLjAxOTk0MDQ2OFoiLCJleHBpcmVkX2F0IjoiMjAyMi0wMy0yOFQxMTozNDo0MS4wMTk5NDA2NDhaIn0.eG8aAoje7s_bENwb06kM1cSgo8y7eJgfOUs-p8KRAaM

###
#searching
GET http://localhost:8080/search?q=https://go.dev/

###
#filter
POST http://localhost:8080/filter

{
    "from_date":"2022-03-28",
    "to_date":"2022-03-29"
}
